name: matchsum
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.12
  - pip
  - pytorch=1.7.1
  - cudatoolkit=11.0
  - pip:
    - fastnlp==0.5.0
    - pyrouge==0.1.3
    - rouge==1.0.0
    - transformers==2.5.1
